name: 'Get Azure App Configuration'
description: 'Pull information from Azure App Configuration'
author: 'David Gardiner'
inputs:
  resourceGroup:
    required: true
    description: 'Resource Group that contains App Configuration resource'
  appConfigurationName:
    required: true
    description: 'Name of App Configuration resource'
  keyFilter:
    required: false
    description: 'Key filter'
  labelFilter:
    required: false
    description: 'Label filter'

branding:
  icon: 'download-cloud'
  color: 'blue'
  
runs:
  using: 'node20'
  main: 'dist/index.js'
