name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
  endpoint:
    required: true
    description: 'URL to Azure App Configuration resource'
runs:
  using: 'node12'
  main: 'dist/index.js'
