name: 'Create PR for dist changes'
on: # manual trigger, which may create PR if any changes
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x
          
      - run: |
          npm ci
      - run: |
          npm run build
          npm run package

      - name: Create Pull Request
        # if: ${{ github.ref == 'refs/heads/main' }}
        uses: peter-evans/create-pull-request@v5.0.0
        with:
          token: ${{ secrets.PAT_REPO_FULL }}
